spring:
  application:
    name: music-stream
  datasource:
    url: jdbc:mysql://localhost:3306/db_music_streaming
    username: root
    password: lequanghuy2212
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  port: 8080
api:
  version: v1
  base-url: /api/${api.version}
open:
  api:
    serverUrl: "http://localhost:8080/"
    serverName: "Development Server"
    title: "Music Streaming API"
    version: "1.0"
    description: "A API for Music Streaming"